### ISSUE TITLE
Authentication error when connecting to mssql database on Azure

### ISSUE THREAD

**Issue by SebastianRehfeldt** [sequelize/sequelize-auto#363] opened 2019-04-29 08:04 UTC
When trying to auto-generate models for a mssql database on Azure, I got the following error:

>  SequelizeConnectionError: Login failed for user ''.
    at Connection.<anonymous> (node_modules\sequelize-auto\node_modules\sequelize\lib\dialects\mssql\connection-manager.js:110:18)
    at Connection.emit (events.js:189:13)
    at Connection.message (node_modules\tedious\lib\connection.js:1972:18)
    at Connection.dispatchEvent (node_modules\tedious\lib\connection.js:1172:36)
    at MessageIO.messageIo.on (node_modules\tedious\lib\connection.js:1045:14)
    at MessageIO.emit (events.js:189:13)
    at Message.message.on (node_modules\tedious\lib\message-io.js:32:14)
    at Message.emit (events.js:194:15)
    at endReadableNT (node_modules\tedious\node_modules\readable-stream\lib\_stream_readable.js:1077:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

The error occured even though a username was set - in both execution from inside code and command line. After some inspection I figured out that the problem lies in the connection-manager.js. The connectionConfig is correct and includes both username and password.
However, after creating the connection, username and password in connection.config.authentication.options are undefined and thus, the connection fails. I fixed this locally by adding the following line before "connection.on('connect', ...":

`connection.config.authentication.options = { userName: connectionConfig.userName, password: connectionConfig.password }`

**Comment by SebastianPfliegel** [comment] 2019-05-23 13:38
Duplicate of issue #360

**Comment by steveschmitt** [comment] 2020-07-05 22:35
I think this is fixed in `sequelize-auto@0.5.0`  
Please try it and close this issue if so.  Thanks!

**Comment by steveschmitt** [comment] 2020-07-10 22:00
Problem was that `sequelize-auto` was using an old version of `sequelize` that was incompatible with current `tedious`

Fixed in `sequelize-auto@0.5.1`

**Closed by steveschmitt** 2020-07-10 22:00 UTC
