### ISSUE TITLE
Support to generate the associate fn when generating models in MSSQL?

### ISSUE THREAD

**Issue by jblaketc** [sequelize/sequelize-auto#65] opened 2016-03-29 16:31 UTC
I'm curious if there's already functionality, on generation, to automatically include any hasMany, hasOne associations in the defines. If there is, it's not working in MSSQL.

If there isn't, it'd be nice to have since, every time I regenerate the models, I have to put back in the associate manually and it's getting tedious. 

Also, as of the current version, what's the way to at least define that logic elsewhere and have it included in generation? The docs make reference of it, but I can't figure out the structure for defining it for multiple models. I can't do it in json because functions aren't valid in .json file format.

For instance, I have these two models that I'm putting the associate fn in manually:

``` javascript
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('UseCase', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    ResourcesID: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'Resource',
        key: 'id'
      }
    },
    Description: {
      type: DataTypes.STRING,
      allowNull: false
    },
    LastTested: {
      type: DataTypes.DATE,
      allowNull: true
    },
    IsSuccess: {
      type: 'BIT',
      allowNull: true
    }
  }, {
    tableName: 'UseCase',
    freezeTableName: true,
    classMethods: {
      associate: function(models) {
        this.hasMany(models.Param);
      }
    }
  });
};
```

``` javascript
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('Param', {
    id: {
      type: DataTypes.INTEGER,
      allowNull: false,
      primaryKey: true
    },
    UseCasesID: {
      type: DataTypes.INTEGER,
      allowNull: false,
      references: {
        model: 'UseCase',
        key: 'id'
      }
    },
    Name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    Value: {
      type: DataTypes.TEXT,
      allowNull: false
    },
    LastTested: {
      type: DataTypes.DATE,
      allowNull: true
    },
    IsSuccess: {
      type: 'BIT',
      allowNull: true
    }
  }, {
    tableName: 'Param',
    freezeTableName: true,
    classMethods: {
      associate: function(models) {
        this.hasMany(models.Content);
      }
    }
  });
};
```

I assume the include file would be something like:

``` javascript
module.exports = {
  'UseCase': {classMethods: {
    associate: function(models){
      this.hasMany(models.Param);
    }
  }},
  'Param': {classMethods: {
    associate: function(models){
      this.hasMany(models.Content);
    }
  }}
}
```

Is that how you structure it so that it'll be included in the generation? A concrete example would help in this situation.

**Comment by NobleUplift** [comment] 2017-06-16 19:53
I've been trying to figure this out for half of this week. Did you ever find a solution to this? When I use hasOne/hasMany, it adds columns to my tables and breaks all my queries.

**Comment by weldermarcosxd** [comment] 2017-07-04 16:13
+1 to this

**Comment by williamluke4** [comment] 2017-10-20 15:06
Any more info on this?

**Comment by NobleUplift** [comment] 2018-04-03 15:38
Is this issue a duplicate of #34?

**Comment by NobleUplift** [comment] 2018-04-03 15:39
This issue is a duplicate of #34.

**Comment by steveschmitt** [comment] 2020-11-04 00:38
Added `belongsTo/hasOne/hasMany` to the generated `initModels` function in release **0.7.0**.

**Closed by steveschmitt** 2020-11-04 00:38 UTC

**Comment by NobleUplift** [comment] 2020-11-23 16:30
AWESOME!!! I can't wait to try it out when I get back to my Sequelize project!
