### ISSUE TITLE
TypeError: connection.query(...).on is not a function

### ISSUE THREAD

**Issue by cybermerlin** [sequelize/sequelize-auto#194] opened 2017-11-03 08:53 UTC
```
sequelize-auto -h 127.0.0.1 -d log-dev -u pguserhipster -x 123 -C -p 5432 -o out -e postgres
```

**Comment by geekflyer** [comment] 2017-11-04 09:44
@cybermerlin encountered the same problem. The root cause is that sequelize doesn't yet support pg@7.x (unfortunately that's nowhere documented). You just have to downgrade to pg@6.4.2 .

**Comment by geekflyer** [comment] 2017-11-04 09:45
actually when using `6.4.2` I'm getting a deprecationwarning which hints on the upcoming problem in in 7.x:
```
DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
```

**Comment by cybermerlin** [comment] 2017-11-16 12:50
unfortunately, I use pg.7 with pg-bricks in other classes (old code)

**Comment by stonedraider** [comment] 2017-12-07 10:10
downgrading to pg@6.4.2 doesn't help for me

**Comment by bpb27** [comment] 2017-12-29 04:06
downgrading worked from me - `npm install -g pg@6.4.2`, using node 8.1.2 and npm 5.5.1

**Comment by jfabiani** [comment] 2018-04-09 23:50
npm install -g pg@6.4.2 does not work for me!  This was very disappointing!

**Comment by Toub** [comment] 2018-05-03 15:01
Downgrading works for me using node v8.9.4 and npm 5.6.0.

**Comment by projetoCopa** [comment] 2018-05-28 18:16
Thanks, npm install -g pg@6.4.2 works for me!

**Comment by steveschmitt** [comment] 2020-07-06 00:22
Fixed in `sequelize-auto@0.5.0`

**Closed by steveschmitt** 2020-07-06 00:22 UTC
