### ISSUE TITLE
paranoid attribute is not being set to true in models

### ISSUE THREAD

**Issue by aeharake** [sequelize/sequelize-auto#544] opened 2021-08-06 18:40 UTC
I have this options.json file:

```
{
  "timestamps": false,
  "deletedAt": "deleted_at",
  "createdAt": "created_at",
  "updatedAt": "updated_at",
  "paranoid": true
}

```

After running the following command:

`sequelize-auto -h 127.0.0.1 -d dbname -u username -x password -p 3306  --dialect mysql -o "./src/database/models" -l ts -a "./src/options.json"`

I should be able to see that paranoid is turned on, however, this is not happening.

**Comment by steveschmitt** [comment] 2021-08-06 18:45
Duplicate of #529

**Comment by aeharake** [comment] 2021-08-06 19:42
> Duplicate of #529

Is anybody working on a fix?

**Comment by steveschmitt** [comment] 2021-08-07 06:02
Fixed in 0.8.4

**Closed by steveschmitt** 2021-08-07 06:02 UTC
