### ISSUE TITLE
what about associations

### ISSUE THREAD

**Issue by anuragnagarkota** [sequelize/sequelize-auto#215] opened 2018-03-11 10:55 UTC
Hey 
Can you add the relationships also, based on foreign keys???
Thanks

**Comment by zypA13510** [comment] 2019-03-13 08:27
Probably a duplicate of #34?

**Comment by steveschmitt** [comment] 2020-11-04 00:36
Added `belongsTo/hasOne/hasMany` to the generated `initModels` function in release **0.7.0**.

**Closed by steveschmitt** 2020-11-04 00:36 UTC
